// src/enemy/enemyTypes.js

export const ENEMY_TYPES = {
  basic: {
    name: "Scout",
    baseHp: 100,
    baseSpeed: 50,
    baseReward: 8,
    radius: 12,
    color: "#7df",
    glowColor: "#48f",
    detailColor: "#5ac",
  },
  brute: {
    name: "Brute",
    baseHp: 180,
    baseSpeed: 40,
    baseReward: 15,
    radius: 16,
    color: "#f96",
    glowColor: "#f63",
    detailColor: "#d54",
  },
  swift: {
    name: "Swift",
    baseHp: 80,
    baseSpeed: 70,
    baseReward: 12,
    radius: 10,
    color: "#9f6",
    glowColor: "#6f3",
    detailColor: "#5d4",
  },
  elite: {
    name: "Elite",
    baseHp: 250,
    baseSpeed: 45,
    baseReward: 25,
    radius: 14,
    color: "#f6f",
    glowColor: "#c3f",
    detailColor: "#a3c",
  },
  sapper: {
    name: "Sapper",
    baseHp: 120,
    baseSpeed: 45,
    baseReward: 20,
    radius: 13,
    color: "#f4a261",
    glowColor: "#e76f51",
    detailColor: "#e9c46a",
    attackRange: 100,
    attackDamage: 15,
    attackRate: 0.8,
    isAttacker: true,
  },
};
