import { GunTower } from "./towers/GunTower.js";
import { CannonTower } from "./towers/CannonTower.js";
import { DoubleCannonTower } from "./towers/DoubleCannonTower.js";
import { LaserTower } from "./towers/LaserTower.js";
import { IceTower } from "./towers/IceTower.js";
import { TeslaTower } from "./towers/TeslaTower.js";
import { PoisonTower } from "./towers/PoisonTower.js";
import { MissileTower } from "./towers/MissileTower.js";
import { FlamethrowerTower } from "./towers/FlamethrowerTower.js";
import { SniperTower } from "./towers/SniperTower.js";
import { ArtilleryTower } from "./towers/ArtilleryTower.js";
import { ArcherTower } from "./towers/ArcherTower.js";
import { LightningTower } from "./towers/LightningTower.js";
import { ShadowTower } from "./towers/ShadowTower.js";
import { WizardTower } from "./towers/WizardTower.js";
import { WindTower } from "./towers/WindTower.js";
import { VolcanoTower } from "./towers/VolcanoTower.js";
import { CarM249Tower } from "./towers/CarM249Tower.js";
import { SmallTank } from "./towers/SmallTank.js";
import { MediumTank } from "./towers/MediumTank.js";
import { BigTank } from "./towers/BigTank.js";
import { BehemothTank } from "./towers/BehemothTank.js";
import { HelicopterTower } from "./towers/HelicopterTower.js";
import { BlackHawkTower } from "./towers/BlackHawkTower.js";
import { JetTower } from "./towers/jet.js";
import { B52SpiritTower } from "./towers/B52SpiritTower.js";

export const TOWER_TYPES = {
  gun: {
    name: "Gunner",
    cost: 80,
    range: 120,
    fireRate: 6,
    dmg: 12,
    bulletSpeed: 340,
    color: "#6cf",
    maxLevel: 10,
    hp: 300,
    unlockPrice: 0, // Default tower
    upgradePriceBase: 25,
    persistentMaxLevel: 100,
    class: GunTower,
  },
  cannon: {
    name: "Cannon",
    cost: 120,
    range: 140,
    fireRate: 1.2,
    dmg: 55,
    splash: 60,
    bulletSpeed: 260,
    color: "#f6c66a",
    maxLevel: 10,
    hp: 300,
    unlockPrice: 200,
    upgradePriceBase: 40,
    persistentMaxLevel: 100,
    class: CannonTower,
  },
  doubleCanon: {
    name: "Double Canon",
    cost: 160,
    range: 120,
    fireRate: 0.9,
    dmg: 75,
    splash: 55,
    bulletSpeed: 240,
    color: "#f00",
    hp: 300,
    maxLevel: 3,
    unlockPrice: 350,
    upgradePriceBase: 55,
    persistentMaxLevel: 50,
    class: DoubleCannonTower,
  },
  laser: {
    name: "Laser",
    cost: 250,
    range: 150,
    fireRate: 12,
    dmg: 5,
    beam: true,
    color: "#ff69e0",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 500,
    upgradePriceBase: 100,
    persistentMaxLevel: 50,
    class: LaserTower,
  },
  ice: {
    name: "Ice",
    cost: 180,
    range: 130,
    fireRate: 2.5,
    dmg: 8,
    slowAmount: 0.6,
    slowDuration: 3,
    freezeChance: 0.2,
    bulletSpeed: 300,
    color: "#6cfaff",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 300,
    upgradePriceBase: 50,
    persistentMaxLevel: 30,
    class: IceTower,
  },
  tesla: {
    name: "Tesla",
    cost: 220,
    range: 140,
    fireRate: 1.8,
    dmg: 25,
    chainCount: 3,
    chainRange: 80,
    stunChance: 0.1,
    stunDuration: 1,
    color: "#9d4edd",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 600,
    upgradePriceBase: 120,
    persistentMaxLevel: 40,
    class: TeslaTower,
  },
  poison: {
    name: "Poison",
    cost: 190,
    range: 110,
    fireRate: 1.5,
    dmg: 15,
    dotDamage: 8,
    dotDuration: 4,
    spreadRange: 60,
    cloudDuration: 3,
    color: "#4CAF50",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 450,
    upgradePriceBase: 70,
    persistentMaxLevel: 50,
    class: PoisonTower,
  },
  missile: {
    name: "Missile",
    cost: 280,
    range: 160,
    fireRate: 0.8,
    dmg: 70,
    splash: 80,
    bulletSpeed: 180,
    homingStrength: 0.1,
    retarget: true,
    color: "#FF5722",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 800,
    upgradePriceBase: 150,
    persistentMaxLevel: 30,
    class: MissileTower,
  },
  flamethrower: {
    name: "Flamethrower",
    cost: 140,
    range: 80,
    fireRate: 15,
    dmg: 8,
    burnDamage: 6,
    burnDuration: 3,
    coneAngle: Math.PI / 3,
    spreadChance: 0.4,
    spreadRange: 40,
    color: "#FF6B35",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 400,
    upgradePriceBase: 65,
    persistentMaxLevel: 60,
    class: FlamethrowerTower,
  },
  sniper: {
    name: "Sniper",
    cost: 350,
    range: 400,
    fireRate: 0.3,
    dmg: 200,
    bulletSpeed: 1200,
    penetration: 2,
    critChance: 0.25,
    critMultiplier: 2.5,
    color: "#2b4ff2",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 1000,
    upgradePriceBase: 200,
    persistentMaxLevel: 25,
    size: { align: "TBLR", occupy: 2 },
    class: SniperTower,
  },
  artillery: {
    name: "Artillery",
    cost: 500,
    range: 350,
    fireRate: 0.15,
    dmg: 60,
    splash: 120,
    bulletSpeed: 150,
    arcHeight: 80,
    minRange: 60,
    color: "#8d6e63",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 1200,
    upgradePriceBase: 250,
    persistentMaxLevel: 20,
    size: { align: "TBLR", occupy: 2 },
    class: ArtilleryTower,
  },
  archer: {
    name: "Archer",
    cost: 90,
    range: 130,
    fireRate: 5,
    dmg: 100,
    bulletSpeed: 400,
    critChance: 0.1,
    critMultiplier: 1.5,
    color: "#8bc34a",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 150,
    upgradePriceBase: 30,
    persistentMaxLevel: 100,
    class: ArcherTower,
  },
  // Add prices to all other towers...
  // (Assuming similar pricing structure for the rest)
  lightning: {
    name: "Lightning",
    cost: 300,
    range: 150,
    fireRate: 1.5,
    dmg: 30,
    chainCount: 4,
    chainRange: 100,
    stunChance: 0.2,
    stunDuration: 1.2,
    color: "#00ffff",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 700,
    upgradePriceBase: 140,
    persistentMaxLevel: 40,
    size: { align: "T", occupy: 2 },
    class: LightningTower,
  },
  shadow: {
    name: "Shadow",
    cost: 320,
    range: 140,
    fireRate: 1.2,
    dmg: 15,
    curseDmg: 5,
    curseDuration: 4,
    chainCount: 3,
    chainRange: 90,
    color: "#800080",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 900,
    upgradePriceBase: 180,
    persistentMaxLevel: 30,
    size: { align: "T", occupy: 2 },
    class: ShadowTower,
  },
  wizard: {
    name: "Wizard",
    cost: 330,
    range: 150,
    fireRate: 1.2,
    dmg: 30,
    chainCount: 2,
    chainRange: 80,
    color: "#7f00ff",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 850,
    upgradePriceBase: 170,
    persistentMaxLevel: 35,
    size: { align: "T", occupy: 2 },
    class: WizardTower,
  },
  wind: {
    name: "Wind",
    cost: 200,
    range: 140,
    fireRate: 1.2,
    knockback: 40,
    slowAmount: 0.5,
    slowDuration: 1.5,
    color: "#00bfff",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 500,
    upgradePriceBase: 100,
    persistentMaxLevel: 20,
    size: { align: "T", occupy: 2 },
    class: WindTower,
  },
  volcano: {
    name: "Volcano",
    cost: 600,
    range: 200,
    fireRate: 0.3,
    dmg: 80,
    splash: 60,
    color: "#ff3300",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 1500,
    upgradePriceBase: 300,
    persistentMaxLevel: 15,
    size: { align: "T", occupy: 2 },
    class: VolcanoTower,
  },
  carM249: {
    name: "Car M249",
    cost: 600,
    range: 180,
    fireRate: 5,
    dmg: 15,
    color: "#2288ff",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 1000,
    upgradePriceBase: 200,
    persistentMaxLevel: 50,
    class: CarM249Tower,
  },
  smallTank: {
    name: "Small Tank",
    cost: 320,
    range: 160,
    fireRate: 1.5,
    dmg: 150,
    splash: 40,
    bulletSpeed: 380,
    color: "#556b2f",
    maxLevel: 3,
    hp: 300,
    unlockPrice: 800,
    upgradePriceBase: 160,
    persistentMaxLevel: 25,
    size: { align: "LR", occupy: 2 },
    class: SmallTank,
  },
  mediumTank: {
    name: "Medium Tank",
    cost: 500,
    range: 180,
    fireRate: 1.0,
    dmg: 300,
    splash: 60,
    bulletSpeed: 300,
    color: "#8b4513",
    maxLevel: 3,
    hp: 3000,
    unlockPrice: 1500,
    upgradePriceBase: 300,
    persistentMaxLevel: 20,
    size: { align: "TBLR", occupy: 2 },
    class: MediumTank,
  },
  bigTank: {
    name: "Big Tank",
    cost: 950,
    range: 200,
    fireRate: 0.6,
    dmg: 600,
    splash: 110,
    bulletSpeed: 220,
    color: "#4b2e1e",
    topFireRate: 10,
    topDmg: 30,
    topBulletSpeed: 720,
    size: { align: "TBLR", occupy: 2 },
    maxLevel: 3,
    hp: 300,
    unlockPrice: 2500,
    upgradePriceBase: 500,
    persistentMaxLevel: 15,
    class: BigTank,
  },
  behemothTank: {
    name: "Behemoth Tank",
    cost: 2200,
    range: 280,
    fireRate: 0.5,
    dmg: 950,
    splash: 140,
    bulletSpeed: 250,
    color: "#a8e0ff",
    topFireRate: 15,
    topDmg: 40,
    maxLevel: 3,
    hp: 300,
    topBulletSpeed: 800,
    size: { align: "TBLR", occupy: 3 },
    unlockPrice: 5000,
    upgradePriceBase: 1000,
    persistentMaxLevel: 10,
    class: BehemothTank,
  },
  helicopter: {
    name: "Heli Pad",
    cost: 1500,
    range: 220,
    fireRate: 12,
    dmg: 35,
    bulletSpeed: 750,
    color: "#ffdd99",
    size: { align: "TBLR", occupy: 1 },
    maxLevel: 3,
    hp: 300,
    unlockPrice: 3000,
    upgradePriceBase: 600,
    persistentMaxLevel: 15,
    class: HelicopterTower,
  },
  blackHawk: {
    name: "Black Hawk",
    cost: 2500,
    range: 280,
    fireRate: 15,
    dmg: 45,
    bulletSpeed: 800,
    color: "#2c3e50",
    size: { align: "TBLR", occupy: 1 },
    maxLevel: 3,
    hp: 300,
    unlockPrice: 4000,
    upgradePriceBase: 800,
    persistentMaxLevel: 15,
    class: BlackHawkTower,
  },
  jet: {
    name: "Stealth Jet",
    cost: 6000,
    range: Infinity,
    fireRate: 0.8,
    dmg: 1000,
    bulletSpeed: 500,
    color: "#34495e",
    maxLevel: 3,
    hp: 300,
    size: { align: "TBLR", occupy: 0 },
    unlockPrice: 10000,
    upgradePriceBase: 2500,
    persistentMaxLevel: 10,
    class: JetTower,
  },
  b52Spirit: {
    name: "B-2 Spirit Bomber",
    cost: 15000,
    range: Infinity,
    fireRate: 0.1,
    dmg: 1000,
    bulletSpeed: 200,
    color: "#495057",
    maxLevel: 3,
    hp: 300,
    size: { align: "TBLR", occupy: 0 },
    unlockPrice: 20000,
    upgradePriceBase: 5000,
    persistentMaxLevel: 5,
    class: B52SpiritTower,
  },
};
